pipeline {
    agent any

    environment {
        cluster = "mbprod"
        service = "mbprodsvc"
    }

    stages {
        stage('Deploy to ECS prod') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-west-2') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
}
